config/routes.rb
Rails.application.routes.draw do
  root to: "movies#index"

  resources :lists
  resources :movies

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post "/list_movies", to: "list_movies#create", as: "create_list_movie"

  # DO NOT MODIFY
  delete "/list_movies", to: "list_movies#destroy", as: "delete_list_movie"
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :list_movies
  has_many :movies, through: :list_movies, dependent: :destroy
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    if valid_list_params?
      if list_params[:movie_id] != nil
        @movie = Movie.find(list_params[:movie_id])
        @movie.lists << @list
      end
      @list = current_user.lists.create(list_params)
      @user = User.find(list_params[:user_id])
      @user.lists << @list

      flash[:notice] = "List successfully created"
      redirect_to @list
    else
      flash[:error] = "List could not be created"
      redirect_to new_list_path
    end

    # respond_to do |format|
    #   if @list.save
    #     format.html { redirect_to @list, notice: 'List was successfully created.' }
    #     format.json { render :show, status: :created, location: @list }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @list.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, :genre, :user_id, :movie_id)
    end

# TEST
    def set_movie_for_list
      if @list
        @selected_movie = @list.movie_id
      elsif params[:movie]
        movie_id = params[:movie]
        @movie = Movie.find(movie_id)
        @selected_movie = @movie.id
      else
        @selected_movie = nil
      end
    end

    def valid_list_params?
      List.new(list_params).valid?
    end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_for(list, class: "form-horizontal") do |f| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, required: true, class: "form-control" %>
  </div>

<!-- this should be a drop down menu -->
  <div class="form-group">
    <%= f.label :genre %>
    <%= f.text_field :genre, autofocus: true, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<div class="container">
  <div class="row">
    <h2 class="text-center">Edit List</h2>
    <br>
    <div class="col-sm-6 col-md-offset-3">

      <%= render 'form', list: @list %>

      <%= link_to 'Show', @list %> |
      <%= link_to 'View All Lists', lists_path %>

    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="text-center">All Lists</h2>
    <br>

    <div class="col-sm-6 col-md-offset-3">
    <table>
      <thead>
        <tr>
          <th>Title</th>
          <br>
          <th>Genre</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% current_user.lists.each do |list| %>
        <tr>
          <td><%= list.title %></td>
          <td><%= list.genre %></td>
          <td><%= link_to 'Show', list %></td>
          <td><%= link_to 'Edit', edit_list_path(list) %></td>
          <td><%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

    <br>

    <%= link_to 'New List', new_list_path %>

  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="row">
    <h2 class="text-center">New List</h2>
    <br>
    <div class="col-sm-6 col-md-offset-3">

      <%= render 'form', list: @list %>

      <%= link_to 'View All Lists', lists_path %>

    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="row">
  <div class="jumbotron text-center">
     <h2><%= @list.title %></h2>
      <h5><%= @list.genre %></h5>
    </div>
  </div>


    <br>


    <div class="pull-right">


      <%= link_to edit_list_path(@list), class: "btn btn-default" do %>
          <i class="glyphicon glyphicon-pencil"></i>
      <% end %>|
      <%= link_to 'Your Lists', lists_path %>
    </div>
    <br>
    <hr>





<% if @list.movies != nil %>

    <% @list.movies.each do |movie| %>
    <div class="col-md-4">
      <h4><%= link_to movie.title.titleize, movie_path(movie) %></h4>
      <% if (movie.tertiary_genre != nil) && (movie.tertiary_genre != "")%>
        <h6> Genres: <%= movie.primary_genre %>, <%= movie.secondary_genre %>, <%= movie.tertiary_genre %></h6>
      <% elsif (movie.secondary_genre != nil) && (movie.secondary_genre != "") %>
        <h6> Genres: <%= movie.primary_genre %>, <%= movie.secondary_genre %> </h6>
      <% elsif (movie.primary_genre != nil) && (movie.primary_genre != "") %>
        <h6> Genre: <%= movie.primary_genre %> </h6>
      <% else %>
        <h6>Genre: No genre listed</h6>
      <% end %>
        <%= link_to delete_list_movie_path(movie) + "?list_id=#{@list.id}&movie_id=#{movie.id}", :method => 'delete', :data => {:confirm => "Are you sure you want to remove #{movie.title}?"}, class: "btn btn-default" do %>
      <i class="glyphicon glyphicon-trash"></i>
      <% end %>
    </div>
    <br>
  <% end %>
<% end %>