config/routes.rb
Rails.application.routes.draw do
  root to: "movies#index"

  resources :lists
  resources :movies

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post "/list_movies", to: "list_movies#create", as: "create_list_movie"

  # DO NOT MODIFY
  delete "/list_movies", to: "list_movies#destroy", as: "delete_list_movie"
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = if params[:title]
      Movie.where('title LIKE ?', "%#{params[:title].downcase.titleize}%").paginate(:page => params[:page], :per_page => 15)
    # elsif
    #   flash[:notice] = 'No search results'
    else
      @movies = Movie.all.paginate(:page => params[:page], :per_page => 15)
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    if current_user == nil
      flash[:notice] = "Log in to put this movie on a list!"
    else
      @lists = current_user.lists
    end
    # @list = List.find(params[:list_id])
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:guidebox_id, :title, :release_date,
    :rating,
    :overview,
    :primary_genre,
    :secondary_genre,
    :tertiary_genre,
    :primary_free_name,
    :primary_free_link,
    :secondary_free_name,
    :secondary_free_link,
    :primary_web_source_name,
    :primary_web_source_link,
    :secondary_web_source_name,
    :secondary_web_source_link,
    :primary_sub_source_name,
    :primary_sub_source_link,
    :secondary_sub_source_name,
    :secondary_sub_source_link,
    :cs_media_link,
    :trailer,
    :sm_img,
    :md_img,
    :lg_img)
      # params.fetch(:movie, {})
    end

    def set_list_for_movie
      if @movie
        @selected_list = @movie.list_id
      elsif params[:list]
        list_id = params[:list]
        @list = List.find(list_id)
        @selected_list = @list.id
      else
        @selected_list = nil
      end
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_add_movie_to_list.html.erb
<% if ((current_user != "") && (current_user != nil) ) %>
    <%= form_tag create_list_movie_path, method: :post %>
            <div class="form-group">
              <% if @lists != nil %>
                <%= select_tag "list_id", options_from_collection_for_select(@lists, "id", "title"), prompt: "Add movie to a list" %>
              <% end %>

            <%= hidden_field_tag :movie_id, @movie.id %>

            <%= button_tag(type: "submit", class: "btn btn-default") do %>
                <i class="glyphicon glyphicon-plus"></i>
            <% end %>
          </div>
    </form>
<% end %>

app/views/movies/_form.html.erb
<%= form_for(movie) do |f| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="text-center">Movies</h2>
    <br>
    <div class="col-sm-6 col-md-offset-3">
  <div class="form-group">
  <%= form_tag(movies_path, method: :get) do %>
  <%= text_field_tag :title, nil, class: "form-control" %></br>
  <%= submit_tag "Search", class:"btn btn-notice btn-block" %>
  <% end %>

    </div>
  </div>
</div>

<br>
<br>

  <% @movies.each do |movie| %>
  <div class="card-group">
    <div class="col-md-4">
      <div class="card card-inverse">
        <%= link_to image_tag(movie.md_img, class: "img-responsive"), movie %>
        <h5><%= movie.title %></h5>
      </div>
    </div>
  </div>
  <% end %>
</div>
<div class="text-center">
  <%= will_paginate @movies %>

</div>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<div class="container">
  <%= link_to 'Back', movies_path %>
  <br>
  <div class="row">
    <div class="col-md-5 col-md-offset-0">
<br>

      <%= image_tag @movie.lg_img, class:"img-responsive"%>

      <div class="row">
        <div class="col-md-12">
          <%= render 'add_movie_to_list', lists: @lists %>


          <% if ((@movie.trailer != "") && (@movie.trailer != nil) ) %>

          <!-- thanks to http://bootsnipp.com/snippets/8Z7b -->
          <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="container iframe-modal">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
              <div class="modal-body">
                <iframe src="<%= @movie.trailer %>" class="iframe" name="info" seamless="" height="100%" width="100%"></iframe>
              </div>
            </div>
          </div>
          <button type="button" class="modalButton btn btn-default" data-toggle="modal"  data-width="0" data-height="0" data-target="#myModal" data-video-fullscreen="">Watch Trailer</button>




      <% end %>

        </div>
        <div class="col-md-12">


        </div>
      </div>
    </div>

<div class="container">
    <div class="col-md-7">
      <div class="row">
        <div class="col-md-12">

          <%= social_share_button_tag(@movie.title, url: movie_path, image: "#{@movie.sm_img}", desc: "You should watch this on Watchable!", via: "Watchable") %>
          <h2><%= @movie.title %></h2>

        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h4>Description</h4>
          <h5 class="overview"> <%= @movie.overview %></h5>

          <div class="col-md-5 col-sm-12">
            <p class="rating">Rating: <%= @movie.rating %></p>
          </div>

          <div class="col-md-7 col-sm-12">
            <p class="genres">
              <% if (@movie.tertiary_genre != nil) && (@movie.tertiary_genre != "") %>
                Genres: <%= @movie.primary_genre %>, <%= @movie.secondary_genre %>, <%= @movie.tertiary_genre %>
              <% elsif (@movie.secondary_genre != nil) && (@movie.secondary_genre != "") %>
              Genres: <%= @movie.primary_genre %>, <%= @movie.secondary_genre %>
              <% elsif (@movie.primary_genre != nil) && (@movie.primary_genre != "")%>
                Genre: <%= @movie.primary_genre %>
              <% else %>
                Genre: Not provided
              <% end %>
            </p>
          </div>

          <div class="col-md-7 offset-col-md-2 col-sm-12">
            <% if (@movie.cs_media_link != nil) && (@movie.cs_media_link != "") %>

            <%= link_to image_tag("http://school.fultonschools.org/es/dunwoodysprings/PublishingImages/_t/Common%20Sense%20Media%20Image_jpg.jpg", class: "img-responsive"), @movie.cs_media_link %>
            <% end %>
          </div>

        </div>

      </div>
          <div class="row">
            <div class="col-md-12">
              <h4>Available on:</h4>

              <% if ((@movie.primary_free_link == "") || (@movie.primary_free_link == nil)) && ((@movie.secondary_free_link == "") || (@movie.secondary_free_link == nil)) && ((@movie.primary_web_source_link == "") || (@movie.primary_web_source_link == nil)) && ((@movie.secondary_web_source_link == "") || (@movie.secondary_web_source_link == nil)) && ((@movie.primary_sub_source_link == "") || (@movie.primary_sub_source_link == nil)) && ((@movie.secondary_sub_source_link == "") || (@movie.secondary_sub_source_link == nil)) %>

                  Cannot be streamed at this time

                <% else %>

                  <% if ((@movie.primary_free_link != "") && (@movie.primary_free_link != nil))%>
                  <div class="col-md-3 col-sm-4 col-xs-6 source-btn">
                    <%= button_to "#{@movie.primary_free_name}", @movie.primary_free_link, :method => "get", class: "btn btn-default" %>
                  </div>
                  <% end %>

                  <% if ((@movie.secondary_free_link != "") && (@movie.secondary_free_link != nil))%>
                    <div class="col-md-3 col-sm-4 col-xs-6 source-btn">
                      <%= button_to "#{@movie.secondary_free_name}", @movie.secondary_free_link, :method => "get", class: "btn btn-default" %>
                    </div>
                  <% end %>

                  <% if ((@movie.primary_web_source_link != "") && (@movie.primary_web_source_link != nil))%>
                    <div class="col-md-3 col-sm-4 col-xs-6 source-btn">
                      <%= button_to "#{@movie.primary_web_source_name}", @movie.primary_web_source_link, :method => "get", class: "btn btn-default" %>
                    </div>
                  <% end %>

                  <% if ((@movie.secondary_web_source_link != "") && (@movie.secondary_web_source_link != nil))%>
                    <div class="col-md-3 col-sm-4 col-xs-6 source-btn">
                      <%= button_to "#{@movie.secondary_web_source_name}", @movie.secondary_web_source_link, :method => "get", class: "btn btn-default" %>
                    </div>
                  <% end %>

                  <% if ((@movie.primary_sub_source_link != "") && (@movie.primary_sub_source_link != nil))%>
                    <div class="col-md-3 col-sm-4 col-xs-6 source-btn">
                      <%= button_to "#{@movie.primary_sub_source_name}", @movie.primary_sub_source_link, :method => "get", class: "btn btn-default" %>
                    </div>
                  <% end %>

                  <% if ((@movie.secondary_sub_source_link != "") && (@movie.secondary_sub_source_link != nil))%>
                    <div class="col-md-3 col-sm-4 col-xs-6 source-btn">
                      <%= button_to "#{@movie.secondary_sub_source_name}", @movie.secondary_sub_source_link, :method => "get", class: "btn btn-default" %>
                    </div>
                  <% end %>

                <% end %>

            </div>
          </div>
        </div>
      </div>
      </div>
      <!-- <div class="page-header">
        <h3>Reviews<button class="btn btn-primary write-review" type="button">Write a review</button></h3></div>
        <div class="media">
          <div class="media-body">
            <h4>Love this!</h4>
            <div><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star-half"></i></div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis maximus nisl ac diam feugiat, non vestibulum libero posuere. Vivamus pharetra leo non nulla egestas, nec malesuada orci finibus. </p>
            <p><span class="reviewer-name"><strong>John Doe</strong></span><span class="review-date">7 Oct 2015</span></p>
          </div>
        </div>
        <div class="media">
          <div class="media-body">
            <h4>Fantastic movie</h4>
            <div><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i></div>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis maximus nisl ac diam feugiat, non vestibulum libero posuere. Vivamus pharetra leo non nulla egestas, nec malesuada orci finibus. </p>
            <p><span class="reviewer-name"><strong>Jane Doe</strong></span><span class="review-date">7 Oct 2015</span></p>
          </div>
        </div>
      </div>

 -->