config/routes.rb
Rails.application.routes.draw do
  root to: "movies#index"

  resources :lists
  resources :movies

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # devise_for :users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post "/list_movies", to: "list_movies#create", as: "create_list_movie"

  # DO NOT MODIFY
  delete "/list_movies", to: "list_movies#destroy", as: "delete_list_movie"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


<head>

  <!-- jQuery Script -->
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

  <!--Import Google Icon Font-->
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

      <!-- <meta charset="utf-8"/>
      <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>

      <meta name="description"/>
      <meta content="width=device-width" name="viewport"/> -->
      <meta name="viewport" content="width=device-width, initial-scale=1">


      <%= javascript_include_tag 'modernizr' %>

      <!-- DO I NEED THIS? -->
      <%= csrf_meta_tag %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    </head>
    <body>


      <nav class="navbar navbar-default navbar-fixed-top navbar-inverse">

        <div class="navbar-header">
          <a class="navbar-brand navbar-link" href="/">Watchable</a>
          <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
        </div>

        <ul class="dropdown-menu">
          <% if user_signed_in? %>
          <%= link_to 'Profile', edit_user_registration_path %>
          <%= link_to 'Sign Out', destroy_user_session_path, :method=>:delete %>
          <% else %>
                      <!-- CONNECT
                    -->
                    <%= link_to 'Sign In', new_user_session_path %>
                    <%= link_to 'Sign Up', new_user_registration_path %>
                    <% end %>
                  </ul>

                  <div class="collapse navbar-collapse" id="navcol-1">
                    <ul class="nav navbar-nav navbar-right">
                      <li class="active" role="presentation">
                       <% if !current_user %>
                       <li role="presentation"><%= link_to "Sign Up", new_user_registration_path %></li>
                       <li role="presentation"><%= link_to "Log In", new_user_session_path %></li>
                       <li><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %></li>
                       <% elsif current_user %>

                       <li role="presentation"><%= link_to "Profile", user_path(current_user) %></li>

                       <li role="presentation"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                       <li role="presentation"><%= link_to 'Create New List', new_list_path %></li>

                     </ul>
                   </li>
                   <% end %>
                 </li>
               </ul>
             </div>
           </div>
         </div>
       </nav>
       <br>
       <br>
       <% flash.each do |name, msg| %>
       <div class="alert <%= name == 'error' ? 'alert-danger' : 'alert-info' %>">
        <div class="container">
          <%= msg %>
        </div>
      </div>
      <% end %>



      <%= yield %>
      <br>
      <br>
      <div class="footer-basic text-center container">
        <footer class="row">
          <ul class="list-inline">
            <li><a href="/">Home</a></li>
          </ul>
          <p class="copyright">Watchable© 2017</p>
        </footer>
      </div>


      <!-- JAVASCRIPT HERE -->
    </body>
    </html>